# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# dotnet build /vagrant_data/LabWebMVC/LabWebMVC.csproj -c Release -o /home/vagrant/app/build
# sudo dotnet publish /vagrant_data/LabWebMVC/LabWebMVC.csproj -c Release -o /var/labwebmvc
$script = <<-SCRIPT 
wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install -y dotnet-sdk-7.0
sudo apt install mc -y
sudo dotnet publish /vagrant_data/LabWebMVC/LabWebMVC.csproj -c Release -o /var/labwebmvc 

yes | sudo cp -i /vagrant_data/kestrel.service /etc/systemd/system/
yes | sudo systemctl enable kestrel.service
sudo systemctl start kestrel.service
SCRIPT
#  
Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/jammy64"
  config.vm.provision "shell", inline: $script, privileged: false
   
  config.vm.box_check_update = false
 
  config.vm.network "public_network",
  ip: "192.168.88.212"
 
 config.vm.synced_folder ".", "/vagrant_data"
 
end
